### PR TITLE
Move packaging to containers and add windows-msi and linux-appimage

### PR DESCRIPTION
**Pull request by jld3103**
Moves all packaging to Docker containers and adds full support for Windows MSI and Linux AppImage installers.

### CODE REVIEW

**Comment by Drakirus** [comment]
Can you separate modifications into separate PRs:
 - Docker needed for containers
 - The move of functions into internal packages
 - The addition of  packaging Windows MSI

**Comment by jld3103** [comment]
I understand what you mean. But would only remove the MSI packaging part and leave the others in this PR

**Comment by Drakirus** [comment]
@jld3103 please wait form https://github.com/go-flutter-desktop/hover/pull/33, I don't want to rebase twice.

hover started as a small project, more and more feature got added in top of the others, and I may confess, the code quality doesn't t match the one on [go-flutter](https://github.com/go-flutter-desktop/go-flutter).

I like the fact that you started moving function into separate files, but there is a lot of things that needs to be discussed first, I don't necessary like the overuse of internal package.
And after a quick look, I spotted some regression. 

I've done some light clean-up in #22.
It adds a convenient `fileutils.CopyTemplate` that replaces to for loop used to write in files.  

regarding moving packaging to containers, same as above, it needs discussion. 

What doesn't needs discussion is windows-msi and linux-appimage.
It will be much easier if you opened a PR containing:
 1) package.go split into multiples files.
 2) linux-appimage
 3) windows-msi

**Comment by jld3103** [comment]
Yeah agree. Just have to look how I can separate the code changes. And yes, I think the code quality is not that great.

**Pull request closed without merging**
