### PR TITLE
Improve icns generation for darwin bundle

### PR DESCRIPTION
**Pull request by jld3103**
Now uses a go library to generate the icns and therefore makes it also possible to generate it on windows.
Thanks @gedw99 https://github.com/go-flutter-desktop/go-flutter/issues/521

### CODE REVIEW

**Comment by gedw99** [comment]
thankyou !

**Comment by GeertJohan** [comment]
Does this mean we can remove icnsutils from the docker image as well?

**Comment by jld3103** [comment]
Ah yes. Missed that

**Comment by GeertJohan** [comment]
Maybe add that change to this PR? Otherwise this LGTM and can be mergend :)

**Comment by jld3103** [comment]
Yes will do it now

**Pull request merged**
