### PR TITLE
README: Add cross-compilation support table

### PR DESCRIPTION
**Pull request by GeertJohan**

### CODE REVIEW

**Comment by GeertJohan** [comment]
I'm not sure that checkmarks in the table are correct now.

**Comment by GeertJohan** [comment]
Related to go-flutter-dekstop/go-flutter##436

**Comment by GeertJohan** [comment]
Related to go-flutter-desktop/go-flutter#436

**Comment by jld3103** [comment]
Nice table!

**Comment by jld3103** [comment]
I think it would look better if rows and columns are switched

**Comment by jld3103** [comment]
I will update the hover docs in the next days and would like to use the table directly, but with more information. So this PR wouldn't be needed anymore.

**Comment by jld3103** [comment]
I think this can be closed, because it's quite outdated. A lot of things have changed by now and it's no longer so easy, because we have AOT now and also AOT cross-compilation. Would you mind closing it if you agree?

**Pull request closed without merging**
