### PR TITLE
add docker proxy flags

### PR DESCRIPTION
**Pull request by nzlov**
fix:
```
https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
```

### CODE REVIEW

**Comment by pchampio** [comment]
With with flag value are you using this flag?
What's the output of `go env` on your host?

Maybe putting `GOPROXY=direct` directly is a better option?
We already have it defined [here](https://github.com/go-flutter-desktop/hover/search?q=GOPROXY%3Ddirect&unscoped_q=GOPROXY%3Ddirect)

**Comment by nzlov** [comment]
go env:
```
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nzlov/Library/Caches/go-build"
GOENV="/Users/nzlov/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nzlov/workspace/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/nzlov/program/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/nzlov/program/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b8/kw3c6tps6l567k8mf4px10sr0000gn/T/go-build972889830=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Fix bug `https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout`  when build windows on macos host.

I can't directly access golang from China.

**Comment by pchampio** [comment]
Do you need both `GOPRIVATE` and `GOPROXY`?
Is this the only place those flags needs to be added, [we use the golang toolkit at others place](https://github.com/go-flutter-desktop/hover/search?q=GOPROXY&unscoped_q=GOPROXY)?

Is exposing another flag relevant?
Wouldn't it much simpler if `go env` -> has `https://goproxy.cn` -> automatically add this flag?

**Comment by nzlov** [comment]
Yes，I need both `GOPRIVATE` and `GOPROXY`.
Auto-add flags are good ideas, but are not implemented yet? not work.

**Comment by nzlov** [comment]
@pchampio I updated the code to get the current environment variables directly into the parameters and automatically delete the docker container.

**Pull request merged**
