### PR TITLE
upgrade docker dependencies

### PR DESCRIPTION
**Pull request by niuhuan**
do list :
1. ubuntu:groovy is too old , the apt-get update has got http status 404, update to ubuntu:focal.
2. add "ENV DEBIAN_FRONTEND=noninteractive" to xarbuilder, skip manual selection  option in order to successfully build docker
3. add "RUN dpkg --add-architecture i386 && apt-get update && apt-get install -y wine32" ,  in order to build exe
4. modify dockercore/golang-cross:1.13.15 to symfonycorp/golang-cross:1.16.3 (upgrade golang)
    - dockercore/golang-cross Dockerfile has borken, because can't download libtool

### CODE REVIEW

**Comment by niuhuan** [comment]
Now I can only build applications that depended go <= 1.13, he target is Windows / Linux.

I'm trying to find new golang-cross docker image.

build darwin log, that was it before
```
docker container: hover: To cross-compile AOT apps for darwin on linux install darling from your package manager or https://www.darlinghq.org/
```

**Comment by jld3103** [comment]
> Now can only build target in Windows / Linux. This happened before I committed. I haven't fixed it yet
> 
> ```
> hover build darwin --docker
> docker container: hover: To cross-compile AOT apps for darwin on linux install darling from your package manager or https://www.darlinghq.org/
> ```

This is intentional. It is not possible to cross-compile darwin in docker.

**Comment by jld3103** [comment]
I had to change the pacman URL to `https://gitlab.archlinux.org/pacman/pacman.git` to make it work, because the old URL redirects and fails.

**Comment by jld3103** [comment]
Everything built successfully, but I don't like the golang-cross docker image. There is no source to it and the version isn't even the latest. I found https://hub.docker.com/r/goreleaser/goreleaser-cross which seems to be actively maintained at https://github.com/goreleaser/goreleaser-cross and supports the latest version. I haven't tried it, but I'd suggest you try that image.

If that image works and you fix the pacman URL, I'll approve the changes and merge.

**Comment by niuhuan** [comment]
I tried goreleaser/goreleaser-cross, some apt packages dependencies has broken.

**Comment by jld3103** [comment]
Can you try fixing it? I the goreleaser image is based on debian buster afaik, the other images were probably based on a different debian version or even on ubuntu.

**Comment by niuhuan** [comment]
latest version based on debian bullseye.

```
# need modify package name 
bsdtar => libarchive-tools
```

but it still not available, I don't know how to fix it

```
#9 175.0 Some packages could not be installed. This may mean that you have
#9 175.0 requested an impossible situation or if you are using the unstable
#9 175.0 distribution that some required packages have not yet been created
#9 175.0 or been moved out of Incoming.
#9 175.0 The following information may help to resolve the situation:
#9 175.0 
#9 175.0 The following packages have unmet dependencies:
#9 175.1  libxft-dev : Depends: libfontconfig1-dev
#9 175.2 E: Unable to correct problems, you have held broken packages.
-
```

**Comment by niuhuan** [comment]
I modify "image form" from "golang-cross" to "golang:1.17.8-buster", that looking good.

"hover build windows --docker" and "hover build linux-appimage --docker", target bin has running on linux/windows well

**Comment by niuhuan** [comment]
A

**Comment by niuhuan** [comment]
> Cross-compiling for windows was never a problem (I think), but you need a cross image to compile for darwin (only debug works with hover)

I am trying add macos build tools refer to golang-cross, how to test it ? run "hover build darwin --docker" ?

**Comment by jld3103** [comment]
`hover build darwin --docker --debug` is what you need to test.

**Comment by niuhuan** [comment]
I can't upgrade the golang or macosxsdk version. 

if using go 1.17 with macosxsdk 10.10
截屏2022-03-12 下午4 19 42


if using go 1.16 with macosxsdk 10.10
截屏2022-03-12 下午7 09 48

if using macosxsdk 11.13
截屏2022-03-13 下午1 41 16

**Comment by niuhuan** [comment]
if macosxsdk version > 10.10 not support o32-clang.  i am used o64-clang

**Comment by niuhuan** [comment]
It's too long, so close

**Pull request closed without merging**
