### PR TITLE
Fix AppImage

### PR DESCRIPTION
**Pull request by jld3103**
Fixes https://github.com/go-flutter-desktop/go-flutter/issues/409

### CODE REVIEW

**Comment by GeertJohan** [comment]
Still WIP?

**Comment by jld3103** [comment]
The fix works, but still there is something broken with submitting an AppImage where it fails because of glibc version mismatch just like snap sadly. Maybe we can fix them both, but this fix works so I think it's not longer WIP.

Just one sec

**Comment by jld3103** [comment]
@GeertJohan Done. Can you review?

**Comment by jld3103** [comment]
> Or: apply these changes to #109, close this PR without merging, and merge 109 when it's done?

I'd prefer this option

**Comment by GeertJohan** [comment]
Converted to draft to avoid accidental merge.

**Pull request closed without merging**
