### PR TITLE
Fix docker GOPROXY

### PR DESCRIPTION
**Pull request by jld3103**

### CODE REVIEW

**Comment by qianniancn** [comment]
Your branch has solved GOPROXY, and now docker cross compilation is no problem.

**Comment by qianniancn** [comment]
images_1

**Comment by jld3103** [comment]
I don't see what the problem is.

**Comment by pchampio** [comment]
> there is no problem with docker cross-compilation

This fixes the issue.

**Comment by qianniancn** [comment]
> > there is no problem with docker cross-compilation
> 
> This fixes the issue.

Yes, the docker problem has been solved

**Comment by jld3103** [comment]
@qianniancn Tagged as `v0.41.4`

**Comment by qianniancn** [comment]
> @qianniancn Tagged as `v0.41.4`

ok

**Pull request merged**
