### PR TITLE
Fix engine download

### PR DESCRIPTION
**Pull request by jld3103**
Fixes https://github.com/go-flutter-desktop/go-flutter/issues/599 on beta channel and also works on master channel.

### CODE REVIEW

**Comment by pchampio** [comment]
Does this work with older engine version download links ?

**Comment by jld3103** [comment]
You mean on stable? I can try

**Comment by jld3103** [comment]
Yep also works on stable. On older version it will not work at some point, because they changed the url at some point, but didn't upload previous releases to it.

**Comment by jld3103** [comment]
But we are targeting beta and even stable works so no problem I think.

**Comment by pchampio** [comment]
So older beta build will not work anymore ?
(I don't think it's an issue)

**Comment by jld3103** [comment]
Yes, but I think it will reach like a few months back

**Comment by pchampio** [comment]
Okay, LGTM!

**Review by pchampio — APPROVED** [review]

**Comment by jld3103** [comment]
Released as ' v0.46.4 '

**Comment by pchampio** [comment]
Humm,
the example github repo is now failing on all CI tasks
Before: https://github.com/go-flutter-desktop/examples/actions/runs/736352408
After: https://github.com/go-flutter-desktop/examples/runs/2825193558?check_suite_focus=true

I don't like this.

**Comment by jld3103** [comment]
all failing? it's only snap and that is broken anyway

**Comment by jld3103** [comment]
will look after that. we should really add ci to this repo as well to catch such things earlier

**Comment by jld3103** [comment]
Oh well renovate doesn't update the Gitub Actions docker image tag

**Comment by jld3103** [comment]
And it didn't fail before because there was no push

**Comment by jld3103** [comment]
https://github.com/go-flutter-desktop/examples/pull/131

**Pull request merged**
